### ISSUE TITLE
what ad5933 module are you exactly using?

### ISSUE THREAD

**Issue by mahansaputra** [debjyotiC/AD5933-MEMS-Cancer-Sensor#1]
i've tried your ad5933 code then upload it to the arduino but it can only read the temperature if i type A or C nothing happens. i'm concern about my ad5933 not working properly. so if i may ask you what exactly ad5933 you are using?

thank you in advance

EDIT: i manage to read the impedance, but i have to change the gain every time i change the Z value. isn't it should be once you know the gain by calculating it the impedance is correct even if we change the Z value?

**Comment by debjyotiC** [comment]
Great! You need to calibrate the Gain value, for calcutating the Z value. A detailed reference is given in the AD5933 datasheet.
[AD5933.pdf](https://github.com/debjyotiC/AD5933-MEMS-Cancer-Sensor/files/3528488/AD5933.pdf)

**Comment by mahansaputra** [comment]
yes i do know that you have to calibrate the gain value to read the correct impedance. but do i have to re calibrate every time i change the impedance value that i'm currently reading? i've read it in a paper that someone wrote, he said to use look up table for the gain value for it to be accurate in reading the impedance. 

thank you for your reply

**Comment by debjyotiC** [comment]
Can you please point me to that paper? And no you dont need to calibrate the AD5933 everytime, but yes if you are doing measurments over a rage of frequencies then there is a seperate callibration procedure but taking two different frequency points, which I think you are aware of!

**Comment by mahansaputra** [comment]
with your code what frequency range you expect for it to correctly measured with only a single gain factor?

edit: also impedance range that you can measure
